wandb_version: 1

architecture:
  desc: null
  value: ResNet18
dataset:
  desc: null
  value: CIFAR10
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 128
device:
  desc: null
  value: cpu
optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714413563.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.9
      5: 0.16.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
